name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup python
      uses: actions/setup-python@5.6.0
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run the Bandit scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Bandit report
      uses: actions/upload-artifact@4.6.2
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build Docker image and run image scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Build the image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Docker Scout scan
        env:
          SUPER_SECRET: ${{ secrets.REPO_PASSWORD }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

          echo $SUPER_SECRET | docker login -u ${{ secrets.REPO_USER }} --password-stdin
          
          docker scout quickview
          docker scout cves
        
